version: '3'
services:
  web_api:
    build:
      context: backend/App
      dockerfile: Dockerfile  
    image: web_api
    ports:
      - 5000
    environment:
      - SERVICE_PORTS=5000
    
  web_app: 
    build:
      context: frontend
      dockerfile: Dockerfile  
    image: frontend
    ports:
      - 5001
    environment:
      - SERVICE_PORTS=5001
      
