version: '3'
services:
  web_api:
    build:
      context: backend
      dockerfile: Dockerfile  
    image: web_api
    ports:
      - 5000
    environment:
      - SERVICE_PORTS=5000
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
  web_app: 
    build:
      context: frontend
      dockerfile: Dockerfile  
    image: frontend
    ports:
      - 5001
    environment:
      - SERVICE_PORTS=5001
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
  proxy:
    image: dockercloud/haproxy
    depends_on:
      - web_api
      - web_app
    environment:
      - BALANCE=leastconn
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:5001
      - 8081:5002
    expose:
      - 5001
      - 5002
      - 8080
      - 8081
    