version: '3'
services:
  web_api:
    build:
      context: backend/App
      dockerfile: Dockerfile  
    image: web_api
    ports:
      - 5000
    environment:
      - SERVICE_PORTS=5000
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
  web_app: 
    build:
      context: frontend
      dockerfile: Dockerfile  
    image: frontend
    ports:
      - 5001
    environment:
      - SERVICE_PORTS=5001
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s